name: Release-plz

on:
  push:
    branches:
      - main

jobs:
  # Release unpublished packages.
  release-plz-release:
    name: Release-plz release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - &checkout
        name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - &install-rust
        name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - &install-linux-deps
        name: Install linux deps
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends libasound2-dev pkg-config
      - name: Run release-plz
        id: release-plz
        uses: release-plz/action@v0.5
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      # Code to run post-release
      #
      # Add youtui release status and version number to use in the next actions
      - name: Check if youtui was released
        id: check_youtui_release
        if: ${{ steps.release-plz.outputs.releases_created }}
        env:
          RELEASES: ${{ steps.release-plz.outputs.releases }}
        run: |
          YOUTUI_IS_RELEASED=$(echo "$RELEASES" | jq -r 'any(.[]; .package_name == "youtui")')
          echo "Checking if youtui was released: $YOUTUI_IS_RELEASED"
          echo "youtui_released=$YOUTUI_IS_RELEASED" >> "$GITHUB_OUTPUT"
          if [ "$YOUTUI_IS_RELEASED" == "true" ]; then
             YOUTUI_VERSION=$(echo "$RELEASES" | jq -r '.[] | select(.package_name == "youtui") | .version')
             echo "released version: $YOUTUI_VERSION"
             echo "youtui_version=$YOUTUI_VERSION" >> "$GITHUB_OUTPUT"
          fi
        
      - name: Setup SSH agent
        if: ${{ steps.check_youtui_release.outputs.youtui_released == 'true' }}
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
      - name: Release youtui to AUR
        if: ${{ steps.check_youtui_release.outputs.youtui_released == 'true' }}
        env:
          NEW_YOUTUI_VERSION: ${{ steps.check_youtui_release.outputs.youtui_version }}
        run: |
          echo "Adding aur to known_hosts"
          # To access aur via ssh aur public key must be added to known hosts
          mkdir -p ~/.ssh
          echo "aur.archlinux.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEuBKrPzbawxA/k2g6NcyV5jmqwJ2s+zpgZGZ7tpLIcN" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

          echo "Installing dependencies for arch docker image"
          docker run --name setup-container \
            -v "${{ github.workspace }}:/workspace" \
            -v "$SSH_AUTH_SOCK:/tmp/ssh_agent.sock" \
            -v "$HOME/.ssh/known_hosts:/etc/ssh/ssh_known_hosts" \
            -e SSH_AUTH_SOCK=/tmp/ssh_agent.sock \
            -e NEW_YOUTUI_VERSION="${{ steps.check_youtui_release.outputs.youtui_version }}" \
            --workdir /workspace \
            archlinux/archlinux:base-devel \
            /bin/bash -c "pacman -Sy --noconfirm git openssh just pacman-contrib"

          echo "Storing setup docker image"
          docker commit setup-container arch-loaded
          docker rm setup-container

          # makepkg commands within justfile need to run as non-root user
          echo "Running aur update under docker image as non-root user"
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -v "$SSH_AUTH_SOCK:/tmp/ssh_agent.sock" \
            -v "$HOME/.ssh/known_hosts:/etc/ssh/ssh_known_hosts" \
            -e SSH_AUTH_SOCK=/tmp/ssh_agent.sock \
            -e NEW_YOUTUI_VERSION="${{ steps.check_youtui_release.outputs.youtui_version }}" \
            --user 1000:1000 \
            --workdir /workspace \
            arch-loaded \
            /bin/bash -c 'just release-youtui-to-aur $NEW_YOUTUI_VERSION'

  # Create a PR with the new versions and changelog, preparing the next release.
  release-plz-pr:
    name: Release-plz PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - *checkout
      - *install-rust
      - *install-linux-deps
      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}


